const CONTENT_CHAPTERS = [
  'agile-methodologies',
  'api-design-patterns',
  'architecture-decision-record',
  'architecture-design',
  'branch-based-testing',
  'branching-strategies',
  'caching',
  'clean-code',
  'code-reviews',
  'debugging',
  'design-patterns',
  'documentation',
  'error-handling',
  'feature-flags',
  'graphql-best-practices',
  'logging',
  'pair-programming',
  'performance-optimization',
  'prompt-engineering',
  'refactoring-techniques',
  'rest-best-practices',
  'technical-debt',
  'testing',
  'version-control-systems',
  'ci-cd',
  'code-quality-metrics',
  'containerization',
  'dependency-management',
  'development-environment-setup',
  'microservices',
  'monitoring-and-observability',
  'security-best-practices',
  'scalability-and-reliability',
];

module.exports = {
  sidebar: [
    'introduction',
    // Sort content chapters alphabetically
    ...CONTENT_CHAPTERS.sort((a, b) => a.localeCompare(b)),
    {
      type: 'category',
      label: 'Appendices',
      items: ['contributors'],
    },
  ],
};
