module.exports = {
  sidebar: [
    'introduction',
    'agile-methodologies',
    'architecture-decision-record',
    'branch-based-testing',
    'branching-strategies',
    'clean-code',
    'code-reviews',
    'debugging',
    'design-patterns',
    'documentation',
    'feature-flags',
    'pair-programming',
    'refactoring-techniques',
    'technical-debt',
    'testing',
    // 'ci-cd',
    // 'automated-testing',
    // 'refactoring',
    // 'test-driven-development',
    // 'behavior-driven-development',
    // 'performance-optimization',
    // 'architecture-design',
    // 'code-quality-metrics',
    // 'microservices',
    // 'containerization',
    // 'dependency-management',
    // 'security-best-practices',
    // 'error-handling',
    // 'logging',
    // 'version-control-systems',
    // 'monitoring-and-observability',
    // 'scalability-and-reliability',
    // 'development-environment-setup',
    {
      type: 'category',
      label: 'Appendices',
      items: ['contributors'],
    },
  ],
};
