const CONTENT_CHAPTERS = [
  'agile-methodologies',
  'architecture-decision-record',
  'architecture-design',
  'branch-based-testing',
  'branching-strategies',
  'clean-code',
  'code-reviews',
  'debugging',
  'design-patterns',
  'documentation',
  'error-handling',
  'feature-flags',
  'logging',
  'pair-programming',
  'performance-optimization',
  'refactoring-techniques',
  'rest-best-practices',
  'technical-debt',
  'testing',
  'version-control-systems',
  'ci-cd',
  // 'automated-testing',
  // 'test-driven-development',
  // 'behavior-driven-development',
  // 'code-quality-metrics',
  // 'microservices',
  // 'containerization',
  // 'dependency-management',
  // 'security-best-practices',
  // 'monitoring-and-observability',
  // 'development-environment-setup',
];

module.exports = {
  sidebar: [
    'introduction',
    // Sort content chapters alphabetically
    ...CONTENT_CHAPTERS.sort((a, b) => a.localeCompare(b)),
    {
      type: 'category',
      label: 'Appendices',
      items: ['contributors'],
    },
  ],
};
